apiVersion: v2
name: smart-autoscaler
description: AI-Powered, Cost-Optimized Kubernetes Autoscaler with Enterprise UI
type: application
version: 0.0.23
appVersion: "0.0.23"
keywords:
  - kubernetes
  - autoscaler
  - hpa
  - cost-optimization
  - finops
  - ai
  - predictive-scaling
maintainers:
  - name: phamngocsonls
home: https://github.com/phamngocsonls/enhanced-smart-k8s-autoscaler
sources:
  - https://github.com/phamngocsonls/enhanced-smart-k8s-autoscaler
