apiVersion: v2
name: smart-autoscaler
description: AI-Powered, Cost-Optimized Kubernetes Autoscaler with Advanced Cost Allocation & Reporting
type: application
version: 0.0.32
appVersion: "0.0.32"
keywords:
  - kubernetes
  - autoscaler
  - hpa
  - cost-optimization
  - finops
  - ai
  - predictive-scaling
  - cost-allocation
  - reporting
maintainers:
  - name: phamngocsonls
home: https://github.com/phamngocsonls/enhanced-smart-k8s-autoscaler
sources:
  - https://github.com/phamngocsonls/enhanced-smart-k8s-autoscaler
