apiVersion: v1
kind: Service
metadata:
  name: smart-autoscaler
  namespace: autoscaler-system
  labels:
    app: smart-autoscaler
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: metrics
  - port: 5000
    targetPort: 5000
    name: dashboard
  selector:
    app: smart-autoscaler
