apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smart-autoscaler
  namespace: autoscaler-system
spec:
  selector:
    matchLabels:
      app: smart-autoscaler
  endpoints:
  - port: metrics
    interval: 30s
