{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smart-autoscaler.serviceAccountName" . }}
  labels:
    {{- include "smart-autoscaler.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "smart-autoscaler.fullname" . }}
  labels:
    {{- include "smart-autoscaler.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "smart-autoscaler.fullname" . }}
  labels:
    {{- include "smart-autoscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "smart-autoscaler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "smart-autoscaler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
